### PR TITLE
Expose recursive-gen combinator

### PR DESCRIPTION
**Pull request by akiellor**
Attempt to expose the cljs recursive combinator.

My flow and typescript definition experience is really limited so I expect the definitions are incorrect.

### CODE REVIEW

**Comment by akiellor** [comment]
Hey @leebyron,

I would really love to migrate from jsverify to testcheck-js in my project for better shrinking support, but really need the recursive-gen combinator.

I more than happy to incorporate any feedback you have for this PR.

Cheers,

Andrew

**Comment by leebyron** [comment]
Sorry for such the long wait for review.

I'm curious if [gen.nested()](http://leebyron.com/testcheck-js/api#gennested) works for you? I don't think I understand exactly how recursive-gen would be different, but I would be happy to add new capabilities if gen.nested wasn't sufficient!

**Comment by akiellor** [comment]
Yep that works! Thanks

**Comment by leebyron** [comment]
Yay!

**Pull request closed without merging**
